prospectiveCustomer -> nexa "Evaluates Nexa and requests contact or a product demonstration" "Browser / HTTPS"
internalTenantWorkforce -> nexa "Uses Nexa according to distinct workforce responsibilities: access governance, company governance, commercial operations, warehouse and dispatch" "Browser / HTTPS"
b2bBuyer -> nexa "Uses private Buyer experiences across authorized Tenant relationships" "Browser / HTTPS"
nexa -> paymentProvider "Uses payment services" "Provider API / HTTPS"
nexa -> emailDeliveryService "Uses email delivery services" "SMTP / provider API"
nexa -> mapsGeolocationProvider "Uses maps and geolocation services" "Provider API / HTTPS"

prospectiveCustomer -> nexa.publicWebsite "Uses" "Browser / HTTPS"
b2bBuyer -> nexa.buyerPortal "Uses" "Browser / HTTPS"
nexa.publicWebsite -> nexa.applicationApi "Submits validated demo/contact requests via HTTPS/JSON" "HTTPS/JSON"
internalTenantWorkforce -> nexa.internalWebPlatform "Uses according to assigned workforce role and permissions" "Browser / HTTPS"
nexa.internalWebPlatform -> nexa.applicationApi "Uses via HTTPS/JSON" "HTTPS/JSON"
nexa.buyerPortal -> nexa.applicationApi "Uses via HTTPS/JSON" "HTTPS/JSON"
nexa.applicationApi -> nexa.postgresqlDatabase "Reads and writes via SQL" "SQL/JDBC"
nexa.applicationApi -> nexa.objectStorage "Stores and retrieves tenant-owned binary assets via S3-compatible API" "S3-compatible API"
nexa.applicationApi -> paymentProvider "Uses payment services through an adapter" "Provider API / HTTPS"
nexa.applicationApi -> emailDeliveryService "Uses email delivery through an adapter" "SMTP / provider API"
nexa.applicationApi -> mapsGeolocationProvider "Owns the maps/geolocation integration boundary through an adapter" "Provider API / HTTPS"
