interestedCompany -> nexa "Discovers product and requests contact/demo" "Browser / HTTPS"
nexaCommercialStaff -> nexa "Processes assisted commercial/onboarding work" "Browser / HTTPS"
companyOwner -> nexa "Governs company and workforce" "Browser / HTTPS"
businessOperationsManager -> nexa "Supervises authorized operations" "Browser / HTTPS"
tenantAdministrator -> nexa "Governs access and capabilities" "Browser / HTTPS"
salesRepresentative -> nexa "Manages customer and commercial work" "Browser / HTTPS"
warehouseOperator -> nexa "Executes authorized warehouse work" "Browser / HTTPS"
dispatchCoordinator -> nexa "Coordinates dispatch and delivery handoff" "Browser / HTTPS"
b2bBuyer -> nexa "Uses authorized Buyer self-service" "Browser / HTTPS"
driverDeliveryOperator -> nexa.operationsMobile "Executes assigned delivery work" "Mobile client / HTTPS"

nexa -> paymentProvider "Uses abstract payment services" "Provider API / HTTPS"
nexa -> emailDeliveryService "Uses abstract email delivery" "Provider API / HTTPS"
nexa -> mapsGeolocationProvider "Uses abstract maps/geolocation services" "Provider API / HTTPS"

interestedCompany -> nexa.publicWebsite "Discovers Nexa and submits public intake" "Browser / HTTPS"
nexaCommercialStaff -> nexa.internalWebPlatform "Uses assisted onboarding surface" "Browser / HTTPS"
companyOwner -> nexa.internalWebPlatform "Uses company governance surface" "Browser / HTTPS"
businessOperationsManager -> nexa.internalWebPlatform "Uses operational overview and decisions" "Browser / HTTPS"
tenantAdministrator -> nexa.internalWebPlatform "Uses access governance surface" "Browser / HTTPS"
salesRepresentative -> nexa.internalWebPlatform "Uses commercial work surface" "Browser / HTTPS"
warehouseOperator -> nexa.internalWebPlatform "Uses warehouse work surface" "Browser / HTTPS"
dispatchCoordinator -> nexa.internalWebPlatform "Uses dispatch work surface" "Browser / HTTPS"
b2bBuyer -> nexa.buyerPortal "Uses Buyer web capabilities" "Browser / HTTPS"

nexa.publicWebsite.websitePublicExperience -> nexa.applicationApi.apiPresentation "Submits validated contact/demo intake" "HTTPS/JSON"
nexa.internalWebPlatform -> nexa.applicationApi "Uses authoritative API contracts" "HTTPS/JSON"
nexa.buyerPortal -> nexa.applicationApi "Uses authoritative Buyer contracts" "HTTPS/JSON"
 nexa.operationsMobile -> nexa.applicationApi "Uses resilient mobile API contracts" "HTTPS/JSON; planned"
 nexa.buyerMobile -> nexa.applicationApi "Uses resilient Buyer API contracts" "HTTPS/JSON; planned"
nexa.applicationApi -> nexa.postgresqlDatabase "Reads and writes scoped transactional state" "SQL/JDBC"
nexa.applicationApi -> nexa.objectStorage "Stores and retrieves authorized evidence and documents" "S3-compatible API"
nexa.applicationApi -> paymentProvider "Uses payment ACL" "Provider API / HTTPS"
nexa.applicationApi -> emailDeliveryService "Uses email ACL" "Provider API / HTTPS"
nexa.applicationApi -> mapsGeolocationProvider "Uses maps/geolocation ACL" "Provider API / HTTPS"

nexa.applicationApi.apiPresentation -> nexa.applicationApi.apiAccessContext "Resolves authenticated identity and requested scope"
nexa.applicationApi.apiPresentation -> nexa.applicationApi.apiApplication "Invokes typed commands and queries"
nexa.applicationApi.apiApplication -> nexa.applicationApi.apiDomain "Applies domain policies and transitions"
nexa.applicationApi.apiApplication -> nexa.applicationApi.apiAccessContext "Requires authorized execution context"
nexa.applicationApi.apiApplication -> nexa.applicationApi.apiPersistence "Uses repositories and transaction ports"
nexa.applicationApi.apiApplication -> nexa.applicationApi.apiIntegrations "Uses provider/device ports"
nexa.applicationApi.apiApplication -> nexa.applicationApi.apiReliability "Records durable facts and projections"
nexa.applicationApi.apiDomain -> nexa.applicationApi.apiReliability "Produces domain facts for publication"
nexa.applicationApi.apiAccessContext -> nexa.applicationApi.apiPersistence "Scopes reads/writes and RLS context"
nexa.applicationApi.apiPersistence -> nexa.postgresqlDatabase "Reads and writes scoped state"
nexa.applicationApi.apiReliability -> nexa.postgresqlDatabase "Stores outbox, inbox, leases and projections"
nexa.applicationApi.apiIntegrations -> paymentProvider "Uses payment ACL"
nexa.applicationApi.apiIntegrations -> emailDeliveryService "Uses email ACL"
nexa.applicationApi.apiIntegrations -> mapsGeolocationProvider "Uses maps/geolocation ACL"
nexa.applicationApi.apiIntegrations -> nexa.objectStorage "Uses storage and evidence ACL"

nexa.internalWebPlatform.platformRouting -> nexa.internalWebPlatform.platformAuthorization "Applies surface/capability navigation"
nexa.internalWebPlatform.platformRouting -> nexa.internalWebPlatform.platformShell "Selects authenticated shell"
nexa.internalWebPlatform.platformShell -> nexa.internalWebPlatform.platformFeatureState "Hosts feature projections"
nexa.internalWebPlatform.platformAuthorization -> nexa.internalWebPlatform.platformFeatureState "Controls action availability"
nexa.internalWebPlatform.platformFeatureState -> nexa.internalWebPlatform.platformApiClients "Loads and mutates API state"
nexa.internalWebPlatform.platformApiClients -> nexa.applicationApi.apiPresentation "Uses HTTP/API contracts"
nexa.internalWebPlatform.platformFeatureState -> nexa.internalWebPlatform.platformSharedExperience "Renders state and accessibility primitives"

nexa.buyerPortal.portalRouting -> nexa.buyerPortal.portalAuthorization "Applies relationship navigation"
nexa.buyerPortal.portalRouting -> nexa.buyerPortal.portalShell "Selects authenticated Buyer shell"
nexa.buyerPortal.portalShell -> nexa.buyerPortal.portalFeatureState "Hosts Buyer projections"
nexa.buyerPortal.portalAuthorization -> nexa.buyerPortal.portalFeatureState "Controls allowed actions"
nexa.buyerPortal.portalFeatureState -> nexa.buyerPortal.portalApiClients "Loads and mutates Buyer API state"
nexa.buyerPortal.portalApiClients -> nexa.applicationApi.apiPresentation "Uses Buyer HTTP/API contracts"
nexa.buyerPortal.portalFeatureState -> nexa.buyerPortal.portalSharedExperience "Renders state and accessibility primitives"

 nexa.operationsMobile.operationsMobileAuth -> nexa.operationsMobile.operationsMobileWork "Controls capability entry"
 nexa.operationsMobile.operationsMobileWork -> nexa.operationsMobile.operationsMobileSync "Queues only explicitly offline-safe work"
 nexa.operationsMobile.operationsMobileWork -> nexa.operationsMobile.operationsMobileEvidence "Requests scan/location/evidence abstractions"
 nexa.operationsMobile.operationsMobileSync -> nexa.applicationApi "Uses idempotent sync contracts"
 nexa.operationsMobile.operationsMobileEvidence -> nexa.applicationApi "Uploads evidence and submits operational facts"
 nexa.buyerMobile.buyerMobileAuth -> nexa.buyerMobile.buyerMobileCommerce "Scopes Buyer actions to active relationship"
 nexa.buyerMobile.buyerMobileCommerce -> nexa.buyerMobile.buyerMobileSync "Publishes safe drafts and push state"
 nexa.buyerMobile.buyerMobileSync -> nexa.applicationApi "Refetches authoritative state"
