internalTenantWorkforce -> nexa.nexaMobile "Future mobile access for selected workforce workflows" "Mobile client / HTTPS"
b2bBuyer -> nexa.nexaMobile "Future mobile access" "Mobile client / HTTPS"
nexa.nexaMobile -> nexa.applicationApi "Future access via HTTPS/JSON" "HTTPS/JSON"
deliveryDriver -> nexa.driverExperience "Future driver workflow" "Mobile client / HTTPS"
nexa.driverExperience -> nexa.applicationApi "Future access via HTTPS/JSON" "HTTPS/JSON"
nexaPlatformAdministrator -> nexa.nexaControlCenter "Future V2 platform administration" "Browser / HTTPS"
nexaSupportSpecialist -> nexa.nexaControlCenter "Future V2 support" "Browser / HTTPS"
nexa.nexaControlCenter -> nexa.applicationApi "Future V2 access via HTTPS/JSON" "HTTPS/JSON"

nexa -> googleIdentityProvider "Future optional identity integration" "Provider API / HTTPS"
nexa -> appleIdentityProvider "Future optional identity integration" "Provider API / HTTPS"
nexa -> linkedinIdentityProvider "Future optional identity integration" "Provider API / HTTPS"
nexa -> iotTelemetryProvider "Future telemetry integration" "Telemetry API / HTTPS"
nexa.applicationApi -> googleIdentityProvider "Future optional identity adapter" "Provider API / HTTPS"
nexa.applicationApi -> appleIdentityProvider "Future optional identity adapter" "Provider API / HTTPS"
nexa.applicationApi -> linkedinIdentityProvider "Future optional identity adapter" "Provider API / HTTPS"
nexa.applicationApi -> iotTelemetryProvider "Future telemetry adapter" "Telemetry API / HTTPS"
