nexa.applicationApi.apiPresentation -> nexa.applicationApi.apiAccessContext "Resolves authenticated identity and requested scope"
nexa.applicationApi.apiPresentation -> nexa.applicationApi.apiApplication "Invokes typed commands and queries"
nexa.applicationApi.apiApplication -> nexa.applicationApi.apiDomain "Applies domain policies and transitions"
nexa.applicationApi.apiApplication -> nexa.applicationApi.apiAccessContext "Requires authorized execution context"
nexa.applicationApi.apiApplication -> nexa.applicationApi.apiPersistence "Uses repositories and transaction ports"
nexa.applicationApi.apiApplication -> nexa.applicationApi.apiIntegrations "Uses provider ports"
nexa.applicationApi.apiApplication -> nexa.applicationApi.apiReliability "Records durable facts and projections"
nexa.applicationApi.apiDomain -> nexa.applicationApi.apiReliability "Produces domain facts for publication"
nexa.applicationApi.apiAccessContext -> nexa.applicationApi.apiPersistence "Scopes reads/writes and RLS context"
nexa.applicationApi.apiPersistence -> nexa.postgresqlDatabase "Reads and writes scoped state"
nexa.applicationApi.apiReliability -> nexa.postgresqlDatabase "Stores outbox, inbox, leases and projections"
nexa.applicationApi.apiIntegrations -> paymentProvider "Uses payment ACL"
nexa.applicationApi.apiIntegrations -> emailDeliveryService "Uses email ACL"
nexa.applicationApi.apiIntegrations -> mapsGeolocationProvider "Uses maps/geolocation ACL"
nexa.applicationApi.apiIntegrations -> nexa.objectStorage "Uses authorized object storage ACL"

nexa.applicationApi.targetCommercialCommitment -> nexa.applicationApi.apiApplication "PRE-V1 target use cases and ports"
nexa.applicationApi.targetCommercialCommitment -> nexa.applicationApi.targetInventoryAvailability "PRE-V1 availability decision contract"
nexa.applicationApi.targetCommercialCommitment -> nexa.applicationApi.targetCreditReceivables "PRE-V1 credit decision contract"
nexa.applicationApi.targetCommercialCommitment -> nexa.applicationApi.apiReliability "Publishes commitment facts"
nexa.applicationApi.targetInventoryAvailability -> nexa.applicationApi.targetFulfillmentDelivery "PRE-V1 allocation execution handoff"
nexa.applicationApi.targetInventoryAvailability -> nexa.applicationApi.apiReliability "Publishes availability facts"
nexa.applicationApi.targetFulfillmentDelivery -> nexa.applicationApi.targetNotificationTraceability "PRE-V1 delivery notification/trace facts"
nexa.applicationApi.targetFulfillmentDelivery -> nexa.applicationApi.targetPaymentDocuments "PRE-V1 evidence/document contract"
nexa.applicationApi.targetCreditReceivables -> nexa.applicationApi.targetPaymentDocuments "PRE-V1 payment/receivable evidence contract"
nexa.applicationApi.targetPaymentDocuments -> nexa.applicationApi.apiIntegrations "Uses provider and storage ACLs"
nexa.applicationApi.targetNotificationTraceability -> nexa.applicationApi.apiReliability "Uses durable publication and change feed"

nexa.internalWebPlatform.platformRouting -> nexa.internalWebPlatform.platformAuthorization "Applies surface/capability navigation"
nexa.internalWebPlatform.platformRouting -> nexa.internalWebPlatform.platformShell "Selects authenticated shell"
nexa.internalWebPlatform.platformShell -> nexa.internalWebPlatform.platformFeatureState "Hosts feature projections"
nexa.internalWebPlatform.platformAuthorization -> nexa.internalWebPlatform.platformFeatureState "Controls action availability"
nexa.internalWebPlatform.platformFeatureState -> nexa.internalWebPlatform.platformApiClients "Loads and mutates API state"
nexa.internalWebPlatform.platformApiClients -> nexa.applicationApi.apiPresentation "Uses HTTP/API contracts"
nexa.internalWebPlatform.platformFeatureState -> nexa.internalWebPlatform.platformSharedExperience "Renders state and accessibility primitives"

nexa.buyerPortal.portalRouting -> nexa.buyerPortal.portalAuthorization "Applies Buyer surface/relationship navigation"
nexa.buyerPortal.portalRouting -> nexa.buyerPortal.portalShell "Selects authenticated Buyer shell"
nexa.buyerPortal.portalShell -> nexa.buyerPortal.portalFeatureState "Hosts Buyer projections"
nexa.buyerPortal.portalAuthorization -> nexa.buyerPortal.portalFeatureState "Controls allowed actions"
nexa.buyerPortal.portalFeatureState -> nexa.buyerPortal.portalApiClients "Loads and mutates Buyer API state"
nexa.buyerPortal.portalApiClients -> nexa.applicationApi.apiPresentation "Uses Buyer HTTP/API contracts"
nexa.buyerPortal.portalFeatureState -> nexa.buyerPortal.portalSharedExperience "Renders state and accessibility primitives"
