-- NEXA TARGET V1 MASTER RELATIONAL MODEL
-- TARGET / shared PostgreSQL / logical BC ownership / no schema-per-BC assumption
-- Generated by concatenating the reviewed per-BC SQL lenses plus shared technical infrastructure.

-- TARGET / BC-01 Tenant & Access Governance / shared PostgreSQL
-- Same-owner foreign keys only. RLS is a deployment policy over tenant_id/workspace_id.

CREATE TABLE tenant (
    tenant_id uuid PRIMARY KEY,
    legal_name varchar(200) NOT NULL,
    slug varchar(100) NOT NULL,
    status varchar(32) NOT NULL CHECK (status IN ('PENDING','ACTIVE','SUSPENDED','CLOSED')),
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    version integer NOT NULL DEFAULT 0 CHECK (version >= 0),
    UNIQUE (slug)
);

CREATE TABLE workspace (
    workspace_id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES tenant (tenant_id),
    name varchar(160) NOT NULL,
    status varchar(32) NOT NULL CHECK (status IN ('ACTIVE','INACTIVE')),
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    version integer NOT NULL DEFAULT 0 CHECK (version >= 0),
    UNIQUE (tenant_id),
    UNIQUE (tenant_id, name)
);

CREATE TABLE human_identity (
    human_identity_id uuid PRIMARY KEY,
    email varchar(320) NOT NULL,
    normalized_email varchar(320) NOT NULL,
    display_name varchar(200),
    status varchar(32) NOT NULL CHECK (status IN ('UNVERIFIED','ACTIVE','DISABLED')),
    verified_at timestamptz,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    UNIQUE (normalized_email)
);

CREATE TABLE company_onboarding_request (
    request_id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES tenant (tenant_id),
    requested_by_identity_id uuid NOT NULL REFERENCES human_identity (human_identity_id),
    legal_name varchar(200) NOT NULL,
    registration_number varchar(80),
    status varchar(32) NOT NULL CHECK (status IN ('DRAFT','SUBMITTED','APPROVED','REJECTED')),
    rejection_reason varchar(500),
    submitted_at timestamptz,
    decided_at timestamptz,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    version integer NOT NULL DEFAULT 0 CHECK (version >= 0)
);

CREATE TABLE workforce_membership (
    membership_id uuid PRIMARY KEY,
    workspace_id uuid NOT NULL REFERENCES workspace (workspace_id),
    human_identity_id uuid NOT NULL REFERENCES human_identity (human_identity_id),
    status varchar(32) NOT NULL CHECK (status IN ('INVITED','ACTIVE','REVOKED')),
    invited_at timestamptz,
    activated_at timestamptz,
    revoked_at timestamptz,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    version integer NOT NULL DEFAULT 0 CHECK (version >= 0),
    UNIQUE (workspace_id, human_identity_id)
);

CREATE TABLE role_definition (
    role_id uuid PRIMARY KEY,
    workspace_id uuid NOT NULL REFERENCES workspace (workspace_id),
    code varchar(80) NOT NULL,
    name varchar(160) NOT NULL,
    status varchar(32) NOT NULL CHECK (status IN ('ACTIVE','RETIRED')),
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    UNIQUE (workspace_id, code)
);

CREATE TABLE capability_definition (
    capability_id uuid PRIMARY KEY,
    code varchar(120) NOT NULL,
    name varchar(200) NOT NULL,
    description varchar(500),
    created_at timestamptz NOT NULL,
    UNIQUE (code)
);

CREATE TABLE membership_role (
    assignment_id uuid PRIMARY KEY,
    membership_id uuid NOT NULL REFERENCES workforce_membership (membership_id),
    role_id uuid NOT NULL REFERENCES role_definition (role_id),
    assigned_at timestamptz NOT NULL,
    removed_at timestamptz,
    UNIQUE (membership_id, role_id)
);

CREATE TABLE role_capability (
    role_capability_id uuid PRIMARY KEY,
    role_id uuid NOT NULL REFERENCES role_definition (role_id),
    capability_id uuid NOT NULL REFERENCES capability_definition (capability_id),
    granted_at timestamptz NOT NULL,
    UNIQUE (role_id, capability_id)
);

CREATE TABLE membership_capability_override (
    override_id uuid PRIMARY KEY,
    membership_id uuid NOT NULL REFERENCES workforce_membership (membership_id),
    capability_id uuid NOT NULL REFERENCES capability_definition (capability_id),
    effect varchar(16) NOT NULL CHECK (effect IN ('ALLOW','DENY')),
    reason varchar(500) NOT NULL,
    expires_at timestamptz,
    created_at timestamptz NOT NULL,
    UNIQUE (membership_id, capability_id)
);

CREATE INDEX ix_workspace_tenant ON workspace (tenant_id);
CREATE INDEX ix_membership_workspace_status ON workforce_membership (workspace_id, status);
CREATE INDEX ix_onboarding_tenant_status ON company_onboarding_request (tenant_id, status);

-- TARGET / BC-02 Customer & Buyer Relationships / shared PostgreSQL
-- human_identity_id, tenant_id and workspace_id are stable non-owning references.

CREATE TABLE customer_account (
    customer_account_id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL,
    workspace_id uuid NOT NULL,
    legal_name varchar(200) NOT NULL,
    tax_identifier varchar(80),
    status varchar(32) NOT NULL CHECK (status IN ('PROSPECT','ACTIVE','SUSPENDED','CLOSED')),
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    version integer NOT NULL DEFAULT 0 CHECK (version >= 0),
    UNIQUE (tenant_id, tax_identifier)
);

CREATE TABLE customer_contact (
    contact_id uuid PRIMARY KEY,
    customer_account_id uuid NOT NULL REFERENCES customer_account (customer_account_id),
    human_identity_id uuid NOT NULL,
    role varchar(32) NOT NULL CHECK (role IN ('BUYER','BILLING','RECEIVING','ADMIN','OTHER')),
    status varchar(32) NOT NULL CHECK (status IN ('ACTIVE','REMOVED')),
    created_at timestamptz NOT NULL,
    UNIQUE (customer_account_id, human_identity_id, role)
);

CREATE TABLE customer_address (
    address_id uuid PRIMARY KEY,
    customer_account_id uuid NOT NULL REFERENCES customer_account (customer_account_id),
    kind varchar(32) NOT NULL CHECK (kind IN ('BILLING','SHIPPING','REGISTERED','OTHER')),
    line1 varchar(240) NOT NULL,
    line2 varchar(240),
    district_code varchar(32),
    province_code varchar(32),
    department_code varchar(32),
    postal_code varchar(32),
    recipient_name varchar(200),
    is_default boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL
);

CREATE TABLE buyer_relationship (
    relationship_id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL,
    workspace_id uuid NOT NULL,
    customer_account_id uuid NOT NULL REFERENCES customer_account (customer_account_id),
    human_identity_id uuid NOT NULL,
    status varchar(32) NOT NULL CHECK (status IN ('PENDING','ACTIVE','SUSPENDED','REVOKED')),
    requested_at timestamptz NOT NULL,
    approved_at timestamptz,
    revoked_at timestamptz,
    version integer NOT NULL DEFAULT 0 CHECK (version >= 0),
    UNIQUE (tenant_id, customer_account_id, human_identity_id)
);

CREATE TABLE buyer_relationship_history (
    history_id uuid PRIMARY KEY,
    relationship_id uuid NOT NULL REFERENCES buyer_relationship (relationship_id),
    from_status varchar(32),
    to_status varchar(32) NOT NULL,
    reason varchar(500),
    changed_by_identity_id uuid,
    changed_at timestamptz NOT NULL
);

CREATE INDEX ix_customer_account_scope_status ON customer_account (tenant_id, workspace_id, status);
CREATE INDEX ix_buyer_relationship_customer ON buyer_relationship (customer_account_id, status);
CREATE INDEX ix_customer_address_account_kind ON customer_address (customer_account_id, kind);

-- TARGET / BC-03 Catalog & Commercial Policy / shared PostgreSQL
-- customer_account_id and sku references to other BCs are stable IDs, not FKs.

CREATE TABLE product (
    product_id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL,
    workspace_id uuid NOT NULL,
    code varchar(80) NOT NULL,
    name varchar(200) NOT NULL,
    description text,
    status varchar(32) NOT NULL CHECK (status IN ('DRAFT','ACTIVE','RETIRED')),
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    version integer NOT NULL DEFAULT 0 CHECK (version >= 0),
    UNIQUE (tenant_id, code)
);

CREATE TABLE sku (
    sku_id uuid PRIMARY KEY,
    product_id uuid NOT NULL REFERENCES product (product_id),
    code varchar(80) NOT NULL,
    name varchar(200) NOT NULL,
    unit_of_measure varchar(32) NOT NULL,
    temperature_band varchar(64) NOT NULL,
    status varchar(32) NOT NULL CHECK (status IN ('DRAFT','ACTIVE','RETIRED')),
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    version integer NOT NULL DEFAULT 0 CHECK (version >= 0),
    UNIQUE (product_id, code)
);

CREATE TABLE catalog_media (
    media_id uuid PRIMARY KEY,
    product_id uuid NOT NULL REFERENCES product (product_id),
    object_key varchar(500) NOT NULL,
    media_kind varchar(32) NOT NULL CHECK (media_kind IN ('IMAGE','DATASHEET','CERTIFICATE','OTHER')),
    content_hash varchar(128),
    sort_order integer NOT NULL DEFAULT 0 CHECK (sort_order >= 0),
    created_at timestamptz NOT NULL
);

CREATE TABLE price_list (
    price_list_id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL,
    workspace_id uuid NOT NULL,
    code varchar(80) NOT NULL,
    name varchar(160) NOT NULL,
    currency char(3) NOT NULL,
    status varchar(32) NOT NULL CHECK (status IN ('DRAFT','ACTIVE','RETIRED')),
    valid_from timestamptz,
    valid_to timestamptz,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    UNIQUE (tenant_id, code),
    CHECK (valid_to IS NULL OR valid_from IS NULL OR valid_to > valid_from)
);

CREATE TABLE price_list_item (
    item_id uuid PRIMARY KEY,
    price_list_id uuid NOT NULL REFERENCES price_list (price_list_id),
    sku_id uuid NOT NULL REFERENCES sku (sku_id),
    unit_price numeric(19,4) NOT NULL CHECK (unit_price >= 0),
    currency char(3) NOT NULL,
    valid_from timestamptz,
    valid_to timestamptz,
    UNIQUE (price_list_id, sku_id),
    CHECK (valid_to IS NULL OR valid_from IS NULL OR valid_to > valid_from)
);

CREATE TABLE base_price (
    base_price_id uuid PRIMARY KEY,
    sku_id uuid NOT NULL REFERENCES sku (sku_id),
    amount numeric(19,4) NOT NULL CHECK (amount >= 0),
    currency char(3) NOT NULL,
    valid_from timestamptz NOT NULL,
    valid_to timestamptz,
    created_at timestamptz NOT NULL,
    CHECK (valid_to IS NULL OR valid_to > valid_from)
);

CREATE TABLE customer_terms (
    terms_id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL,
    workspace_id uuid NOT NULL,
    customer_account_id uuid NOT NULL,
    price_list_id uuid REFERENCES price_list (price_list_id),
    credit_days integer NOT NULL DEFAULT 0 CHECK (credit_days >= 0),
    currency char(3) NOT NULL,
    valid_from timestamptz NOT NULL,
    valid_to timestamptz,
    created_at timestamptz NOT NULL,
    CHECK (valid_to IS NULL OR valid_to > valid_from)
);

CREATE TABLE promotion (
    promotion_id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL,
    workspace_id uuid NOT NULL,
    code varchar(80) NOT NULL,
    name varchar(160) NOT NULL,
    status varchar(32) NOT NULL CHECK (status IN ('DRAFT','SCHEDULED','ACTIVE','EXPIRED','RETIRED')),
    starts_at timestamptz NOT NULL,
    ends_at timestamptz NOT NULL,
    max_stackable boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    UNIQUE (tenant_id, code),
    CHECK (ends_at > starts_at)
);

CREATE TABLE promotion_sku (
    promotion_sku_id uuid PRIMARY KEY,
    promotion_id uuid NOT NULL REFERENCES promotion (promotion_id),
    sku_id uuid NOT NULL REFERENCES sku (sku_id),
    discount_kind varchar(32) NOT NULL CHECK (discount_kind IN ('PERCENT','FIXED')),
    discount_value numeric(19,4) NOT NULL CHECK (discount_value > 0),
    UNIQUE (promotion_id, sku_id)
);

CREATE INDEX ix_sku_product_status ON sku (product_id, status);
CREATE INDEX ix_price_list_item_sku ON price_list_item (sku_id);
CREATE INDEX ix_base_price_sku_validity ON base_price (sku_id, valid_from, valid_to);
CREATE INDEX ix_promotion_scope_status ON promotion (tenant_id, status, starts_at, ends_at);

-- TARGET / BC-04 Sales Commitment / shared PostgreSQL
-- buyer_relationship_id and sku_id are stable non-owning BC references.

CREATE TABLE request_draft (
    draft_id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL,
    workspace_id uuid NOT NULL,
    buyer_relationship_id uuid NOT NULL,
    status varchar(32) NOT NULL CHECK (status IN ('DRAFT','SUBMITTED','ABANDONED')),
    expires_at timestamptz,
    created_by_identity_id uuid NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    version integer NOT NULL DEFAULT 0 CHECK (version >= 0)
);

CREATE TABLE request_draft_line (
    line_id uuid PRIMARY KEY,
    draft_id uuid NOT NULL REFERENCES request_draft (draft_id),
    sku_id uuid NOT NULL,
    quantity numeric(19,6) NOT NULL CHECK (quantity > 0),
    notes varchar(500),
    UNIQUE (draft_id, sku_id)
);

CREATE TABLE purchase_request (
    purchase_request_id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL,
    workspace_id uuid NOT NULL,
    buyer_relationship_id uuid NOT NULL,
    status varchar(32) NOT NULL CHECK (status IN ('SUBMITTED','CHANGES_PROPOSED','CONVERTED','REJECTED','WITHDRAWN','EXPIRED')),
    submitted_at timestamptz NOT NULL,
    expires_at timestamptz NOT NULL,
    revision integer NOT NULL DEFAULT 0 CHECK (revision >= 0),
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    CHECK (expires_at > submitted_at)
);

CREATE TABLE purchase_request_line (
    line_id uuid PRIMARY KEY,
    purchase_request_id uuid NOT NULL REFERENCES purchase_request (purchase_request_id),
    sku_id uuid NOT NULL,
    requested_quantity numeric(19,6) NOT NULL CHECK (requested_quantity > 0),
    accepted_quantity numeric(19,6) CHECK (accepted_quantity IS NULL OR accepted_quantity > 0),
    price_snapshot jsonb NOT NULL,
    terms_snapshot jsonb NOT NULL,
    UNIQUE (purchase_request_id, sku_id)
);

CREATE TABLE material_change_proposal (
    proposal_id uuid PRIMARY KEY,
    purchase_request_id uuid NOT NULL REFERENCES purchase_request (purchase_request_id),
    proposed_by_identity_id uuid NOT NULL,
    status varchar(32) NOT NULL CHECK (status IN ('PROPOSED','ACCEPTED','REJECTED','EXPIRED')),
    change_snapshot jsonb NOT NULL,
    proposed_at timestamptz NOT NULL,
    decided_at timestamptz
);

CREATE TABLE commercial_commitment (
    commitment_id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL,
    workspace_id uuid NOT NULL,
    -- Origin discriminator avoids a polymorphic source FK. DIRECT_ORDER is
    -- represented by the confirmed SalesOrder created in the same decision.
    origin_type varchar(32) NOT NULL CHECK (origin_type IN ('PURCHASE_REQUEST','DIRECT_ORDER')),
    purchase_request_id uuid REFERENCES purchase_request (purchase_request_id),
    buyer_relationship_id uuid NOT NULL,
    status varchar(32) NOT NULL CHECK (status IN ('ESTABLISHED','CONFIRMED','CANCELLED','REPLACED')),
    committed_at timestamptz NOT NULL,
    cancelled_at timestamptz,
    revision integer NOT NULL DEFAULT 0 CHECK (revision >= 0),
    CHECK (
        (origin_type = 'PURCHASE_REQUEST' AND purchase_request_id IS NOT NULL)
        OR (origin_type = 'DIRECT_ORDER' AND purchase_request_id IS NULL)
    ),
    UNIQUE (purchase_request_id)
);

CREATE TABLE commercial_commitment_line (
    line_id uuid PRIMARY KEY,
    commitment_id uuid NOT NULL REFERENCES commercial_commitment (commitment_id),
    sku_id uuid NOT NULL,
    quantity numeric(19,6) NOT NULL CHECK (quantity > 0),
    unit_price numeric(19,4) NOT NULL CHECK (unit_price >= 0),
    currency char(3) NOT NULL,
    terms_snapshot jsonb NOT NULL,
    UNIQUE (commitment_id, sku_id)
);

CREATE TABLE sales_order (
    sales_order_id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL,
    workspace_id uuid NOT NULL,
    commitment_id uuid NOT NULL REFERENCES commercial_commitment (commitment_id),
    status varchar(32) NOT NULL CHECK (status IN ('CONFIRMED','IN_FULFILLMENT','PARTIALLY_FULFILLED','FULFILLED','PARTIALLY_DELIVERED','COMPLETED','CANCELLED')),
    confirmed_at timestamptz NOT NULL,
    cancelled_at timestamptz,
    revision integer NOT NULL DEFAULT 0 CHECK (revision >= 0),
    UNIQUE (commitment_id)
);

CREATE TABLE sales_order_line (
    line_id uuid PRIMARY KEY,
    sales_order_id uuid NOT NULL REFERENCES sales_order (sales_order_id),
    sku_id uuid NOT NULL,
    quantity numeric(19,6) NOT NULL CHECK (quantity > 0),
    unit_price numeric(19,4) NOT NULL CHECK (unit_price >= 0),
    currency char(3) NOT NULL,
    fulfillment_quantity numeric(19,6) NOT NULL DEFAULT 0 CHECK (fulfillment_quantity >= 0 AND fulfillment_quantity <= quantity),
    UNIQUE (sales_order_id, sku_id)
);

CREATE TABLE commitment_owner_transfer (
    transfer_id uuid PRIMARY KEY,
    commitment_id uuid NOT NULL REFERENCES commercial_commitment (commitment_id),
    from_owner varchar(32) NOT NULL CHECK (from_owner IN ('PURCHASE_REQUEST','COMMERCIAL_COMMITMENT')),
    to_owner varchar(32) NOT NULL CHECK (to_owner IN ('COMMERCIAL_COMMITMENT','SALES_ORDER')),
    transferred_at timestamptz NOT NULL,
    reason varchar(500) NOT NULL
);

CREATE TABLE sales_commitment_adjustment (
    adjustment_id uuid PRIMARY KEY,
    commitment_id uuid NOT NULL REFERENCES commercial_commitment (commitment_id),
    reason varchar(500) NOT NULL,
    quantity_delta numeric(19,6) NOT NULL CHECK (quantity_delta <> 0),
    amount_delta numeric(19,4) NOT NULL,
    created_by_identity_id uuid NOT NULL,
    created_at timestamptz NOT NULL
);

CREATE INDEX ix_request_draft_scope_status ON request_draft (tenant_id, workspace_id, status);
CREATE INDEX ix_purchase_request_scope_status ON purchase_request (tenant_id, workspace_id, status, expires_at);
CREATE INDEX ix_commitment_scope_status ON commercial_commitment (tenant_id, workspace_id, status);
CREATE INDEX ix_sales_order_scope_status ON sales_order (tenant_id, workspace_id, status);

-- TARGET / BC-05 Inventory Availability / shared PostgreSQL
-- commitment_id and sku_id are stable non-owning references; local FKs are warehouse-owned.

CREATE TABLE warehouse (
    warehouse_id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL,
    workspace_id uuid NOT NULL,
    code varchar(80) NOT NULL,
    name varchar(160) NOT NULL,
    status varchar(32) NOT NULL CHECK (status IN ('ACTIVE','INACTIVE')),
    timezone varchar(80) NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    version integer NOT NULL DEFAULT 0 CHECK (version >= 0),
    UNIQUE (tenant_id, code)
);

CREATE TABLE inventory_lot (
    lot_id uuid PRIMARY KEY,
    warehouse_id uuid NOT NULL REFERENCES warehouse (warehouse_id),
    sku_id uuid NOT NULL,
    lot_code varchar(120) NOT NULL,
    expires_at timestamptz,
    on_hand_quantity numeric(19,6) NOT NULL DEFAULT 0 CHECK (on_hand_quantity >= 0),
    held_quantity numeric(19,6) NOT NULL DEFAULT 0 CHECK (held_quantity >= 0),
    status varchar(32) NOT NULL CHECK (status IN ('AVAILABLE','HOLD','QUARANTINE','DAMAGED','WASTE','EXPIRED','IN_TRANSIT')),
    received_at timestamptz NOT NULL,
    version integer NOT NULL DEFAULT 0 CHECK (version >= 0),
    UNIQUE (warehouse_id, lot_code)
);

CREATE TABLE inventory_position (
    position_id uuid PRIMARY KEY,
    warehouse_id uuid NOT NULL REFERENCES warehouse (warehouse_id),
    sku_id uuid NOT NULL,
    on_hand_quantity numeric(19,6) NOT NULL DEFAULT 0 CHECK (on_hand_quantity >= 0),
    reserved_quantity numeric(19,6) NOT NULL DEFAULT 0 CHECK (reserved_quantity >= 0),
    held_quantity numeric(19,6) NOT NULL DEFAULT 0 CHECK (held_quantity >= 0),
    version integer NOT NULL DEFAULT 0 CHECK (version >= 0),
    UNIQUE (warehouse_id, sku_id),
    CHECK (reserved_quantity <= on_hand_quantity),
    CHECK (held_quantity <= on_hand_quantity)
);

CREATE TABLE inventory_movement (
    movement_id uuid PRIMARY KEY,
    warehouse_id uuid NOT NULL REFERENCES warehouse (warehouse_id),
    lot_id uuid REFERENCES inventory_lot (lot_id),
    sku_id uuid NOT NULL,
    kind varchar(32) NOT NULL CHECK (kind IN ('RECEIPT','RESERVATION','RELEASE','PICK','ADJUSTMENT','TRANSFER_OUT','TRANSFER_IN','DISPOSAL')),
    quantity numeric(19,6) NOT NULL CHECK (quantity > 0),
    reference_type varchar(80),
    reference_id uuid,
    occurred_at timestamptz NOT NULL
);

CREATE TABLE safety_stock_policy (
    policy_id uuid PRIMARY KEY,
    warehouse_id uuid NOT NULL REFERENCES warehouse (warehouse_id),
    sku_id uuid NOT NULL,
    minimum_quantity numeric(19,6) NOT NULL CHECK (minimum_quantity >= 0),
    valid_from timestamptz NOT NULL,
    valid_to timestamptz,
    UNIQUE (warehouse_id, sku_id, valid_from),
    CHECK (valid_to IS NULL OR valid_to > valid_from)
);

CREATE TABLE inventory_backing (
    backing_id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL,
    workspace_id uuid NOT NULL,
    commercial_commitment_id uuid NOT NULL,
    status varchar(32) NOT NULL CHECK (status IN ('REQUESTED','BACKED','RELEASED','CONSUMED','FAILED')),
    requested_at timestamptz NOT NULL,
    completed_at timestamptz,
    version integer NOT NULL DEFAULT 0 CHECK (version >= 0),
    UNIQUE (commercial_commitment_id)
);

CREATE TABLE inventory_backing_line (
    line_id uuid PRIMARY KEY,
    backing_id uuid NOT NULL REFERENCES inventory_backing (backing_id),
    sku_id uuid NOT NULL,
    requested_quantity numeric(19,6) NOT NULL CHECK (requested_quantity > 0),
    backed_quantity numeric(19,6) NOT NULL DEFAULT 0 CHECK (backed_quantity >= 0 AND backed_quantity <= requested_quantity),
    UNIQUE (backing_id, sku_id)
);

CREATE TABLE physical_allocation (
    allocation_id uuid PRIMARY KEY,
    backing_id uuid NOT NULL REFERENCES inventory_backing (backing_id),
    status varchar(32) NOT NULL CHECK (status IN ('ALLOCATED','RELEASED','CONSUMED')),
    allocated_at timestamptz NOT NULL,
    released_at timestamptz
);

CREATE TABLE physical_allocation_line (
    line_id uuid PRIMARY KEY,
    allocation_id uuid NOT NULL REFERENCES physical_allocation (allocation_id),
    lot_id uuid NOT NULL REFERENCES inventory_lot (lot_id),
    sku_id uuid NOT NULL,
    quantity numeric(19,6) NOT NULL CHECK (quantity > 0),
    consumed_quantity numeric(19,6) NOT NULL DEFAULT 0 CHECK (consumed_quantity >= 0 AND consumed_quantity <= quantity),
    UNIQUE (allocation_id, lot_id)
);

CREATE TABLE inventory_adjustment (
    adjustment_id uuid PRIMARY KEY,
    warehouse_id uuid NOT NULL REFERENCES warehouse (warehouse_id),
    lot_id uuid REFERENCES inventory_lot (lot_id),
    sku_id uuid NOT NULL,
    quantity_delta numeric(19,6) NOT NULL CHECK (quantity_delta <> 0),
    reason varchar(500) NOT NULL,
    status varchar(32) NOT NULL CHECK (status IN ('PENDING','APPROVED','APPLIED','REJECTED')),
    requested_by_identity_id uuid NOT NULL,
    approved_at timestamptz,
    applied_at timestamptz
);

CREATE TABLE warehouse_transfer (
    transfer_id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL,
    workspace_id uuid NOT NULL,
    source_warehouse_id uuid NOT NULL REFERENCES warehouse (warehouse_id),
    destination_warehouse_id uuid NOT NULL REFERENCES warehouse (warehouse_id),
    status varchar(32) NOT NULL CHECK (status IN ('REQUESTED','IN_TRANSIT','RECEIVED')),
    requested_at timestamptz NOT NULL,
    in_transit_at timestamptz,
    received_at timestamptz,
    CHECK (source_warehouse_id <> destination_warehouse_id)
);

CREATE TABLE warehouse_transfer_line (
    line_id uuid PRIMARY KEY,
    transfer_id uuid NOT NULL REFERENCES warehouse_transfer (transfer_id),
    sku_id uuid NOT NULL,
    quantity numeric(19,6) NOT NULL CHECK (quantity > 0),
    received_quantity numeric(19,6) NOT NULL DEFAULT 0 CHECK (received_quantity >= 0 AND received_quantity <= quantity),
    UNIQUE (transfer_id, sku_id)
);

CREATE TABLE lot_disposition (
    disposition_id uuid PRIMARY KEY,
    lot_id uuid NOT NULL REFERENCES inventory_lot (lot_id),
    kind varchar(32) NOT NULL CHECK (kind IN ('HOLD','RELEASE','DISPOSE','RETURN')),
    reason varchar(500) NOT NULL,
    quantity numeric(19,6) NOT NULL CHECK (quantity > 0),
    created_by_identity_id uuid NOT NULL,
    created_at timestamptz NOT NULL
);

CREATE INDEX ix_inventory_lot_fefo ON inventory_lot (warehouse_id, sku_id, expires_at, status);
CREATE INDEX ix_inventory_position_sku ON inventory_position (warehouse_id, sku_id);
CREATE INDEX ix_inventory_movement_reference ON inventory_movement (reference_type, reference_id);
CREATE INDEX ix_backing_commitment_status ON inventory_backing (commercial_commitment_id, status);
CREATE INDEX ix_transfer_scope_status ON warehouse_transfer (tenant_id, workspace_id, status);

-- TARGET / BC-06 Fulfillment & Delivery / shared PostgreSQL
-- sales_order_id, physical_allocation_id and sku_id are stable non-owning references.

CREATE TABLE fulfillment (
    fulfillment_id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL,
    workspace_id uuid NOT NULL,
    sales_order_id uuid NOT NULL,
    status varchar(32) NOT NULL CHECK (status IN ('PLANNED','ALLOCATED','PICKING','PICKED','PACKED','STAGED','READY_FOR_DISPATCH','HANDED_OVER','COMPLETED','SHORTAGE','HOLD','CANCELLED')),
    planned_at timestamptz NOT NULL,
    started_at timestamptz,
    completed_at timestamptz,
    version integer NOT NULL DEFAULT 0 CHECK (version >= 0)
);

CREATE TABLE fulfillment_line (
    line_id uuid PRIMARY KEY,
    fulfillment_id uuid NOT NULL REFERENCES fulfillment (fulfillment_id),
    sku_id uuid NOT NULL,
    physical_allocation_id uuid NOT NULL,
    planned_quantity numeric(19,6) NOT NULL CHECK (planned_quantity > 0),
    picked_quantity numeric(19,6) NOT NULL DEFAULT 0 CHECK (picked_quantity >= 0 AND picked_quantity <= planned_quantity),
    UNIQUE (fulfillment_id, sku_id)
);

CREATE TABLE picking_result (
    picking_result_id uuid PRIMARY KEY,
    fulfillment_id uuid NOT NULL REFERENCES fulfillment (fulfillment_id),
    status varchar(32) NOT NULL CHECK (status IN ('STARTED','CONFIRMED','DISCREPANCY')),
    picker_identity_id uuid NOT NULL,
    started_at timestamptz NOT NULL,
    completed_at timestamptz
);

CREATE TABLE picking_discrepancy (
    discrepancy_id uuid PRIMARY KEY,
    picking_result_id uuid NOT NULL REFERENCES picking_result (picking_result_id),
    fulfillment_line_id uuid NOT NULL REFERENCES fulfillment_line (line_id),
    kind varchar(32) NOT NULL CHECK (kind IN ('SHORT','DAMAGED','WRONG_LOT','OTHER')),
    quantity numeric(19,6) NOT NULL CHECK (quantity > 0),
    resolution varchar(500),
    resolved_at timestamptz
);

CREATE TABLE delivery (
    delivery_id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL,
    workspace_id uuid NOT NULL,
    fulfillment_id uuid NOT NULL REFERENCES fulfillment (fulfillment_id),
    status varchar(32) NOT NULL CHECK (status IN ('PLANNED','ASSIGNED','DISPATCHED','IN_TRANSIT','PARTIAL','DELIVERED','FAILED','CANCELLED')),
    destination_snapshot jsonb NOT NULL,
    scheduled_at timestamptz,
    dispatched_at timestamptz,
    delivered_at timestamptz,
    version integer NOT NULL DEFAULT 0 CHECK (version >= 0)
);

CREATE TABLE delivery_assignment (
    assignment_id uuid PRIMARY KEY,
    delivery_id uuid NOT NULL REFERENCES delivery (delivery_id),
    operator_id uuid NOT NULL,
    vehicle_reference varchar(120),
    assigned_at timestamptz NOT NULL,
    unassigned_at timestamptz
);

CREATE TABLE delivery_attempt (
    attempt_id uuid PRIMARY KEY,
    delivery_id uuid NOT NULL REFERENCES delivery (delivery_id),
    attempt_number integer NOT NULL CHECK (attempt_number > 0),
    outcome varchar(32) NOT NULL CHECK (outcome IN ('PENDING','DELIVERED','PARTIAL','FAILED','REFUSED','ABSENT')),
    attempted_at timestamptz NOT NULL,
    notes varchar(1000),
    UNIQUE (delivery_id, attempt_number)
);

CREATE TABLE delivery_attempt_line (
    line_id uuid PRIMARY KEY,
    attempt_id uuid NOT NULL REFERENCES delivery_attempt (attempt_id),
    fulfillment_line_id uuid NOT NULL REFERENCES fulfillment_line (line_id),
    sku_id uuid NOT NULL,
    attempted_quantity numeric(19,6) NOT NULL CHECK (attempted_quantity > 0),
    received_quantity numeric(19,6) NOT NULL DEFAULT 0 CHECK (received_quantity >= 0 AND received_quantity <= attempted_quantity),
    UNIQUE (attempt_id, fulfillment_line_id)
);

CREATE TABLE delivery_quantity_outcome (
    outcome_id uuid PRIMARY KEY,
    attempt_id uuid NOT NULL REFERENCES delivery_attempt (attempt_id),
    sku_id uuid NOT NULL,
    fulfilled_quantity numeric(19,6) NOT NULL DEFAULT 0 CHECK (fulfilled_quantity >= 0),
    short_quantity numeric(19,6) NOT NULL DEFAULT 0 CHECK (short_quantity >= 0),
    reason varchar(500),
    UNIQUE (attempt_id, sku_id)
);

CREATE TABLE proof_of_delivery (
    pod_id uuid PRIMARY KEY,
    delivery_id uuid NOT NULL REFERENCES delivery (delivery_id),
    status varchar(32) NOT NULL CHECK (status IN ('CAPTURED','SEALED','REJECTED')),
    recipient_name varchar(200),
    signature_object_key varchar(500),
    captured_at timestamptz NOT NULL,
    sealed_at timestamptz,
    UNIQUE (delivery_id)
);

CREATE TABLE proof_of_delivery_addendum (
    addendum_id uuid PRIMARY KEY,
    pod_id uuid NOT NULL REFERENCES proof_of_delivery (pod_id),
    reason varchar(500) NOT NULL,
    evidence_object_key varchar(500),
    appended_by_identity_id uuid NOT NULL,
    appended_at timestamptz NOT NULL
);

CREATE TABLE temperature_evidence (
    evidence_id uuid PRIMARY KEY,
    delivery_id uuid NOT NULL REFERENCES delivery (delivery_id),
    captured_at timestamptz NOT NULL,
    temperature_celsius numeric(8,3) NOT NULL,
    source varchar(80) NOT NULL,
    evidence_metadata jsonb,
    UNIQUE (delivery_id, captured_at, source)
);

CREATE TABLE temperature_excursion (
    excursion_id uuid PRIMARY KEY,
    delivery_id uuid NOT NULL REFERENCES delivery (delivery_id),
    evidence_id uuid REFERENCES temperature_evidence (evidence_id),
    status varchar(32) NOT NULL CHECK (status IN ('OPEN','HOLD','DISPOSITIONED','CLOSED')),
    reason varchar(500) NOT NULL,
    opened_at timestamptz NOT NULL,
    closed_at timestamptz
);

CREATE TABLE continuation_delivery (
    continuation_id uuid PRIMARY KEY,
    parent_delivery_id uuid NOT NULL REFERENCES delivery (delivery_id),
    status varchar(32) NOT NULL CHECK (status IN ('OPEN','DISPATCHED','COMPLETED','CANCELLED')),
    remaining_snapshot jsonb NOT NULL,
    opened_at timestamptz NOT NULL,
    closed_at timestamptz
);

CREATE INDEX ix_fulfillment_scope_status ON fulfillment (tenant_id, workspace_id, status);
CREATE INDEX ix_delivery_scope_status ON delivery (tenant_id, workspace_id, status);
CREATE INDEX ix_delivery_attempt_delivery ON delivery_attempt (delivery_id, attempt_number);
CREATE INDEX ix_temperature_evidence_delivery_time ON temperature_evidence (delivery_id, captured_at);

-- TARGET / BC-07 Credit & Receivables / shared PostgreSQL
-- customer_account_id, commitment_id, payment_id and document_id are stable IDs.

CREATE TABLE credit_account (
    credit_account_id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL,
    workspace_id uuid NOT NULL,
    customer_account_id uuid NOT NULL,
    credit_limit numeric(19,4) NOT NULL CHECK (credit_limit >= 0),
    currency char(3) NOT NULL,
    status varchar(32) NOT NULL CHECK (status IN ('PENDING','ACTIVE','SUSPENDED','CLOSED')),
    approved_at timestamptz,
    version integer NOT NULL DEFAULT 0 CHECK (version >= 0),
    UNIQUE (tenant_id, customer_account_id)
);

CREATE TABLE credit_reservation (
    reservation_id uuid PRIMARY KEY,
    credit_account_id uuid NOT NULL REFERENCES credit_account (credit_account_id),
    commercial_commitment_id uuid NOT NULL,
    amount numeric(19,4) NOT NULL CHECK (amount > 0),
    currency char(3) NOT NULL,
    status varchar(32) NOT NULL CHECK (status IN ('ACTIVE','RELEASED','CONSUMED','EXPIRED')),
    reserved_at timestamptz NOT NULL,
    released_at timestamptz,
    UNIQUE (credit_account_id, commercial_commitment_id)
);

CREATE TABLE receivable (
    receivable_id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL,
    workspace_id uuid NOT NULL,
    customer_account_id uuid NOT NULL,
    sales_order_id uuid,
    business_document_id uuid,
    original_amount numeric(19,4) NOT NULL CHECK (original_amount > 0),
    outstanding_amount numeric(19,4) NOT NULL CHECK (outstanding_amount >= 0 AND outstanding_amount <= original_amount),
    currency char(3) NOT NULL,
    due_at timestamptz NOT NULL,
    status varchar(32) NOT NULL CHECK (status IN ('OPEN','PARTIALLY_SETTLED','SETTLED','WRITTEN_OFF')),
    issued_at timestamptz NOT NULL,
    version integer NOT NULL DEFAULT 0 CHECK (version >= 0)
);

CREATE TABLE receivable_application (
    application_id uuid PRIMARY KEY,
    receivable_id uuid NOT NULL REFERENCES receivable (receivable_id),
    payment_id uuid NOT NULL,
    amount numeric(19,4) NOT NULL CHECK (amount > 0),
    currency char(3) NOT NULL,
    applied_at timestamptz NOT NULL,
    reversed_at timestamptz,
    UNIQUE (receivable_id, payment_id)
);

CREATE TABLE financial_adjustment (
    adjustment_id uuid PRIMARY KEY,
    receivable_id uuid NOT NULL REFERENCES receivable (receivable_id),
    kind varchar(32) NOT NULL CHECK (kind IN ('INCREASE','DECREASE','WRITE_OFF','CORRECTION')),
    amount numeric(19,4) NOT NULL CHECK (amount > 0),
    currency char(3) NOT NULL,
    reason varchar(500) NOT NULL,
    status varchar(32) NOT NULL CHECK (status IN ('PENDING','APPROVED','POSTED','REJECTED')),
    created_by_identity_id uuid NOT NULL,
    created_at timestamptz NOT NULL,
    posted_at timestamptz
);

CREATE TABLE financial_ledger_entry (
    entry_id uuid PRIMARY KEY,
    receivable_id uuid NOT NULL REFERENCES receivable (receivable_id),
    adjustment_id uuid REFERENCES financial_adjustment (adjustment_id),
    application_id uuid REFERENCES receivable_application (application_id),
    direction varchar(16) NOT NULL CHECK (direction IN ('DEBIT','CREDIT')),
    amount numeric(19,4) NOT NULL CHECK (amount > 0),
    currency char(3) NOT NULL,
    posted_at timestamptz NOT NULL
);

CREATE INDEX ix_credit_account_scope_status ON credit_account (tenant_id, workspace_id, status);
CREATE INDEX ix_credit_reservation_commitment_status ON credit_reservation (commercial_commitment_id, status);
CREATE INDEX ix_receivable_scope_due_status ON receivable (tenant_id, workspace_id, due_at, status);
CREATE INDEX ix_ledger_receivable_time ON financial_ledger_entry (receivable_id, posted_at);

-- TARGET / BC-08 Payments / shared PostgreSQL
-- Provider payload is immutable evidence; external commercial/financial IDs are not FKs.

CREATE TABLE payment (
    payment_id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL,
    workspace_id uuid NOT NULL,
    customer_account_id uuid NOT NULL,
    commercial_commitment_id uuid,
    receivable_id uuid,
    amount numeric(19,4) NOT NULL CHECK (amount > 0),
    currency char(3) NOT NULL,
    method varchar(32) NOT NULL CHECK (method IN ('CARD','TRANSFER','CASH','OTHER')),
    status varchar(32) NOT NULL CHECK (status IN ('INITIATED','AUTHORIZED','CONFIRMED','FAILED','CANCELLED','REFUNDED','PARTIALLY_REFUNDED')),
    initiated_at timestamptz NOT NULL,
    confirmed_at timestamptz,
    version integer NOT NULL DEFAULT 0 CHECK (version >= 0)
);

CREATE TABLE payment_attempt (
    attempt_id uuid PRIMARY KEY,
    payment_id uuid NOT NULL REFERENCES payment (payment_id),
    provider_code varchar(80) NOT NULL,
    provider_reference varchar(200),
    status varchar(32) NOT NULL CHECK (status IN ('STARTED','AUTHORIZED','DECLINED','ERROR')),
    attempted_at timestamptz NOT NULL,
    completed_at timestamptz
);

CREATE TABLE payment_provider_event (
    event_id uuid PRIMARY KEY,
    payment_id uuid REFERENCES payment (payment_id),
    provider_code varchar(80) NOT NULL,
    provider_event_id varchar(240) NOT NULL,
    event_type varchar(120) NOT NULL,
    payload jsonb NOT NULL,
    payload_hash varchar(128) NOT NULL,
    received_at timestamptz NOT NULL,
    UNIQUE (provider_code, provider_event_id)
);

CREATE TABLE payment_refund (
    refund_id uuid PRIMARY KEY,
    payment_id uuid NOT NULL REFERENCES payment (payment_id),
    amount numeric(19,4) NOT NULL CHECK (amount > 0),
    currency char(3) NOT NULL,
    status varchar(32) NOT NULL CHECK (status IN ('REQUESTED','PROCESSING','COMPLETED','FAILED')),
    reason varchar(500) NOT NULL,
    requested_at timestamptz NOT NULL,
    completed_at timestamptz
);

CREATE TABLE payment_correction (
    correction_id uuid PRIMARY KEY,
    payment_id uuid NOT NULL REFERENCES payment (payment_id),
    amount_delta numeric(19,4) NOT NULL CHECK (amount_delta <> 0),
    reason varchar(500) NOT NULL,
    status varchar(32) NOT NULL CHECK (status IN ('PENDING','APPROVED','POSTED','REJECTED')),
    created_by_identity_id uuid NOT NULL,
    created_at timestamptz NOT NULL,
    posted_at timestamptz
);

CREATE TABLE payment_reconciliation_case (
    case_id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL,
    workspace_id uuid NOT NULL,
    payment_id uuid NOT NULL REFERENCES payment (payment_id),
    reason varchar(500) NOT NULL,
    status varchar(32) NOT NULL CHECK (status IN ('OPEN','INVESTIGATING','RESOLVED','CLOSED')),
    opened_at timestamptz NOT NULL,
    resolved_at timestamptz
);

CREATE INDEX ix_payment_scope_status ON payment (tenant_id, workspace_id, status);
CREATE INDEX ix_payment_attempt_payment ON payment_attempt (payment_id, attempted_at);
CREATE INDEX ix_provider_event_payment_time ON payment_provider_event (payment_id, received_at);
CREATE INDEX ix_reconciliation_scope_status ON payment_reconciliation_case (tenant_id, workspace_id, status);

-- TARGET / BC-09 Business Documents / shared PostgreSQL
-- Business bytes live in Object Storage; only immutable metadata is relational.

CREATE TABLE document_number_series (
    series_id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL,
    workspace_id uuid NOT NULL,
    document_type varchar(32) NOT NULL,
    series_code varchar(32) NOT NULL,
    next_number bigint NOT NULL CHECK (next_number > 0),
    version integer NOT NULL DEFAULT 0 CHECK (version >= 0),
    UNIQUE (tenant_id, workspace_id, document_type, series_code)
);

CREATE TABLE business_document (
    document_id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL,
    workspace_id uuid NOT NULL,
    series_id uuid NOT NULL REFERENCES document_number_series (series_id),
    document_type varchar(32) NOT NULL,
    document_number varchar(80) NOT NULL,
    sales_order_id uuid,
    payment_id uuid,
    receivable_id uuid,
    status varchar(32) NOT NULL CHECK (status IN ('DRAFT','ISSUED','VOID','SUPERSEDED')),
    issued_at timestamptz,
    voided_at timestamptz,
    UNIQUE (tenant_id, document_type, document_number)
);

CREATE TABLE document_snapshot_line (
    line_id uuid PRIMARY KEY,
    document_id uuid NOT NULL REFERENCES business_document (document_id),
    sku_id uuid,
    sku_code varchar(80),
    description varchar(500) NOT NULL,
    quantity numeric(19,6) NOT NULL CHECK (quantity > 0),
    unit_price numeric(19,4) NOT NULL CHECK (unit_price >= 0),
    currency char(3) NOT NULL,
    line_total numeric(19,4) NOT NULL CHECK (line_total >= 0)
);

CREATE TABLE document_revision (
    revision_id uuid PRIMARY KEY,
    document_id uuid NOT NULL REFERENCES business_document (document_id),
    revision_number integer NOT NULL CHECK (revision_number > 0),
    snapshot_hash varchar(128) NOT NULL,
    created_by_identity_id uuid NOT NULL,
    created_at timestamptz NOT NULL,
    UNIQUE (document_id, revision_number),
    UNIQUE (document_id, snapshot_hash)
);

CREATE TABLE object_storage_reference (
    object_reference_id uuid PRIMARY KEY,
    document_id uuid NOT NULL REFERENCES business_document (document_id),
    object_key varchar(500) NOT NULL,
    content_type varchar(160) NOT NULL,
    content_length bigint NOT NULL CHECK (content_length >= 0),
    content_hash varchar(128) NOT NULL,
    created_at timestamptz NOT NULL,
    UNIQUE (object_key),
    UNIQUE (document_id, content_hash)
);

CREATE TABLE document_generation_request (
    generation_request_id uuid PRIMARY KEY,
    document_id uuid NOT NULL REFERENCES business_document (document_id),
    status varchar(32) NOT NULL CHECK (status IN ('QUEUED','PROCESSING','COMPLETED','FAILED')),
    requested_at timestamptz NOT NULL,
    completed_at timestamptz,
    failure_reason varchar(500),
    object_reference_id uuid REFERENCES object_storage_reference (object_reference_id)
);

CREATE INDEX ix_business_document_scope_type ON business_document (tenant_id, workspace_id, document_type, status);
CREATE INDEX ix_document_revision_document ON document_revision (document_id, revision_number);
CREATE INDEX ix_generation_request_status ON document_generation_request (status, requested_at);

-- TARGET / BC-10 Notifications / shared PostgreSQL
-- event_id and recipient identity references are stable IDs; source business truth stays upstream.

CREATE TABLE notification_template (
    template_id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL,
    workspace_id uuid NOT NULL,
    event_type varchar(160) NOT NULL,
    channel varchar(32) NOT NULL CHECK (channel IN ('EMAIL','IN_APP')),
    version integer NOT NULL CHECK (version > 0),
    content_snapshot jsonb NOT NULL,
    status varchar(32) NOT NULL CHECK (status IN ('DRAFT','PUBLISHED','RETIRED')),
    created_at timestamptz NOT NULL,
    UNIQUE (tenant_id, workspace_id, event_type, channel, version)
);

CREATE TABLE notification (
    notification_id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL,
    workspace_id uuid NOT NULL,
    template_id uuid REFERENCES notification_template (template_id),
    event_id uuid NOT NULL,
    event_type varchar(160) NOT NULL,
    status varchar(32) NOT NULL CHECK (status IN ('SCHEDULED','PROCESSING','DELIVERED','PARTIAL','FAILED','CANCELLED')),
    scheduled_at timestamptz NOT NULL,
    delivered_at timestamptz,
    version integer NOT NULL DEFAULT 0 CHECK (version >= 0)
);

CREATE TABLE notification_recipient (
    recipient_id uuid PRIMARY KEY,
    notification_id uuid NOT NULL REFERENCES notification (notification_id),
    recipient_key varchar(240) NOT NULL,
    channel_address varchar(320) NOT NULL,
    status varchar(32) NOT NULL CHECK (status IN ('PENDING','SENT','FAILED','SUPPRESSED')),
    created_at timestamptz NOT NULL,
    UNIQUE (notification_id, recipient_key)
);

CREATE TABLE notification_preference (
    preference_id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL,
    workspace_id uuid NOT NULL,
    recipient_key varchar(240) NOT NULL,
    event_type varchar(160) NOT NULL,
    channel varchar(32) NOT NULL CHECK (channel IN ('EMAIL','IN_APP')),
    enabled boolean NOT NULL,
    updated_at timestamptz NOT NULL,
    UNIQUE (tenant_id, workspace_id, recipient_key, event_type, channel)
);

CREATE TABLE notification_attempt (
    attempt_id uuid PRIMARY KEY,
    notification_id uuid NOT NULL REFERENCES notification (notification_id),
    recipient_id uuid NOT NULL REFERENCES notification_recipient (recipient_id),
    channel varchar(32) NOT NULL CHECK (channel IN ('EMAIL','IN_APP')),
    status varchar(32) NOT NULL CHECK (status IN ('STARTED','SUCCEEDED','FAILED')),
    provider_reference varchar(240),
    failure_reason varchar(500),
    attempted_at timestamptz NOT NULL
);

CREATE INDEX ix_notification_scope_status ON notification (tenant_id, workspace_id, status, scheduled_at);
CREATE INDEX ix_notification_recipient_status ON notification_recipient (notification_id, status);
CREATE INDEX ix_notification_attempt_retry ON notification_attempt (notification_id, attempted_at);

-- TARGET / BC-11 Business Traceability / shared PostgreSQL
-- Append-only business facts; source aggregate IDs and evidence references are stable IDs.

CREATE TABLE business_traceability_record (
    traceability_id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL,
    workspace_id uuid,
    event_id uuid NOT NULL,
    event_type varchar(160) NOT NULL,
    aggregate_type varchar(120) NOT NULL,
    aggregate_id uuid NOT NULL,
    actor_id uuid,
    payload jsonb NOT NULL,
    occurred_at timestamptz NOT NULL,
    recorded_at timestamptz NOT NULL,
    payload_hash varchar(128) NOT NULL,
    UNIQUE (tenant_id, event_id),
    UNIQUE (tenant_id, aggregate_type, aggregate_id, event_id)
);

CREATE TABLE traceability_evidence_reference (
    evidence_reference_id uuid PRIMARY KEY,
    traceability_id uuid NOT NULL REFERENCES business_traceability_record (traceability_id),
    evidence_kind varchar(32) NOT NULL CHECK (evidence_kind IN ('DOCUMENT','OBJECT','API_REQUEST','USER_ACTION','PROVIDER_EVENT','OTHER')),
    source_reference varchar(500) NOT NULL,
    content_hash varchar(128),
    created_at timestamptz NOT NULL
);

CREATE INDEX ix_traceability_scope_time ON business_traceability_record (tenant_id, occurred_at);
CREATE INDEX ix_traceability_aggregate_time ON business_traceability_record (aggregate_type, aggregate_id, occurred_at);
CREATE INDEX ix_traceability_evidence_record ON traceability_evidence_reference (traceability_id);

-- TARGET / Shared Technical Infrastructure / shared PostgreSQL
-- Technical reliability tables are not a Bounded Context and do not own business aggregates.

CREATE TABLE outbox_event (
    outbox_event_id uuid PRIMARY KEY,
    tenant_id uuid,
    workspace_id uuid,
    event_type varchar(160) NOT NULL,
    aggregate_type varchar(120) NOT NULL,
    aggregate_id uuid NOT NULL,
    payload jsonb NOT NULL,
    occurred_at timestamptz NOT NULL,
    published_at timestamptz,
    attempt_count integer NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
    next_attempt_at timestamptz,
    last_error varchar(500),
    dead_lettered_at timestamptz
);

CREATE TABLE inbox_deduplication (
    inbox_id uuid PRIMARY KEY,
    consumer_name varchar(160) NOT NULL,
    message_id uuid NOT NULL,
    tenant_id uuid,
    workspace_id uuid,
    received_at timestamptz NOT NULL,
    processed_at timestamptz,
    next_attempt_at timestamptz,
    lease_until timestamptz,
    claim_token varchar(240),
    attempt_count integer NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
    last_error varchar(500),
    dead_lettered_at timestamptz,
    status varchar(32) NOT NULL CHECK (status IN ('RECEIVED','PROCESSING','PROCESSED','FAILED','DEAD_LETTER')),
    UNIQUE (consumer_name, message_id)
);

CREATE TABLE idempotency_record (
    idempotency_id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL,
    workspace_id uuid,
    actor_id uuid,
    scope_key varchar(240) NOT NULL,
    operation_name varchar(160) NOT NULL,
    idempotency_key varchar(240) NOT NULL,
    request_hash varchar(128) NOT NULL,
    state varchar(32) NOT NULL CHECK (state IN ('PROCESSING','COMPLETED','FAILED','CONFLICT','EXPIRED')),
    response_status integer,
    response_snapshot jsonb,
    failure_code varchar(160),
    created_at timestamptz NOT NULL,
    completed_at timestamptz,
    expires_at timestamptz NOT NULL,
    UNIQUE (scope_key, operation_name, idempotency_key)
);

CREATE TABLE worker_lease (
    lease_id uuid PRIMARY KEY,
    worker_name varchar(160) NOT NULL,
    queue_name varchar(160) NOT NULL,
    item_id uuid NOT NULL,
    tenant_id uuid,
    workspace_id uuid,
    lease_token varchar(240) NOT NULL,
    fencing_version bigint NOT NULL CHECK (fencing_version > 0),
    status varchar(32) NOT NULL CHECK (status IN ('CLAIMED','RELEASED','EXPIRED','DEAD_LETTER')),
    acquired_at timestamptz NOT NULL,
    expires_at timestamptz NOT NULL,
    attempt_count integer NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
    next_attempt_at timestamptz,
    last_error varchar(500),
    UNIQUE (queue_name, item_id)
);

CREATE TABLE security_audit_event (
    security_audit_event_id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL,
    workspace_id uuid,
    actor_id uuid,
    action varchar(160) NOT NULL,
    resource_type varchar(120),
    resource_id uuid,
    outcome varchar(32) NOT NULL CHECK (outcome IN ('SUCCESS','DENIED','ERROR')),
    metadata jsonb,
    occurred_at timestamptz NOT NULL
);

CREATE INDEX ix_outbox_unpublished ON outbox_event (published_at, occurred_at);
CREATE INDEX ix_outbox_retry ON outbox_event (published_at, next_attempt_at, occurred_at);
CREATE INDEX ix_inbox_consumer_status ON inbox_deduplication (consumer_name, status, next_attempt_at, received_at);
CREATE INDEX ix_idempotency_scope_operation ON idempotency_record (scope_key, operation_name, state, expires_at);
CREATE INDEX ix_lease_claimable ON worker_lease (queue_name, status, next_attempt_at, expires_at);
CREATE INDEX ix_security_audit_scope_time ON security_audit_event (tenant_id, occurred_at);
