interestedCompany -> nexa "Discovers product and requests contact/demo" "Browser / HTTPS"
nexaCommercialStaff -> nexa "Processes assisted commercial/onboarding work" "Browser / HTTPS"
companyOwner -> nexa "Governs company and workforce" "Browser / HTTPS"
businessOperationsManager -> nexa "Supervises authorized operations" "Browser / HTTPS"
tenantAdministrator -> nexa "Governs access and capabilities" "Browser / HTTPS"
salesRepresentative -> nexa "Manages customer and commercial work" "Browser / HTTPS"
warehouseOperator -> nexa "Executes authorized warehouse work" "Browser / HTTPS"
dispatchCoordinator -> nexa "Coordinates dispatch and delivery handoff" "Browser / HTTPS"
b2bBuyer -> nexa "Uses authorized Buyer self-service" "Browser / HTTPS"
driverDeliveryOperator -> nexa.operationsMobile "Executes assigned delivery work" "Mobile client / HTTPS"

nexa -> paymentProvider "Uses abstract payment services" "Provider API / HTTPS"
nexa -> emailDeliveryService "Uses abstract email delivery" "Provider API / HTTPS"
nexa -> mapsGeolocationProvider "Uses abstract maps/geolocation services" "Provider API / HTTPS"
nexa -> pushDeliveryService "Future/open provider runway; selection and Product channel acceptance remain open" "Provider API / HTTPS; future"

interestedCompany -> nexa.publicWebsite "Discovers Nexa and submits public intake" "Browser / HTTPS"
nexaCommercialStaff -> nexa.internalWebPlatform "Uses assisted onboarding surface" "Browser / HTTPS"
companyOwner -> nexa.internalWebPlatform "Uses company governance surface" "Browser / HTTPS"
businessOperationsManager -> nexa.internalWebPlatform "Uses operational overview and decisions" "Browser / HTTPS"
tenantAdministrator -> nexa.internalWebPlatform "Uses access governance surface" "Browser / HTTPS"
salesRepresentative -> nexa.internalWebPlatform "Uses commercial work surface" "Browser / HTTPS"
warehouseOperator -> nexa.internalWebPlatform "Uses warehouse work surface" "Browser / HTTPS"
dispatchCoordinator -> nexa.internalWebPlatform "Uses dispatch work surface" "Browser / HTTPS"
b2bBuyer -> nexa.buyerPortal "Uses Buyer web capabilities" "Browser / HTTPS"
b2bBuyer -> nexa.buyerMobile "Uses V1 TARGET Buyer Mobile capabilities" "Mobile client / HTTPS; target"
salesRepresentative -> nexa.operationsMobile "Uses V1 TARGET field-sales capabilities" "Mobile client / HTTPS; target"
warehouseOperator -> nexa.operationsMobile "Uses V1 TARGET warehouse capabilities" "Mobile client / HTTPS; target"
dispatchCoordinator -> nexa.operationsMobile "Uses V1 TARGET dispatch capabilities" "Mobile client / HTTPS; target"
businessOperationsManager -> nexa.operationsMobile "Uses V1 TARGET operational oversight capabilities" "Mobile client / HTTPS; target"

nexa.publicWebsite.websitePublicExperience -> nexa.applicationApi.apiPresentation "Submits validated contact/demo intake" "HTTPS/JSON"
nexa.internalWebPlatform -> nexa.applicationApi "Uses authoritative API contracts" "HTTPS/JSON"
nexa.buyerPortal -> nexa.applicationApi "Uses authoritative Buyer contracts" "HTTPS/JSON"
 nexa.operationsMobile -> nexa.applicationApi "Uses authoritative API contracts; explicit retries refetch and revalidate server state" "HTTPS/JSON; V1 TARGET"
 nexa.buyerMobile -> nexa.applicationApi "Uses authoritative Buyer API contracts; fresh state is refetched from the server" "HTTPS/JSON; V1 TARGET"
nexa.internalWebPlatform -> nexa.applicationApi.apiPresentation "Uses authoritative API presentation contracts" "HTTPS/JSON"
nexa.buyerPortal -> nexa.applicationApi.apiPresentation "Uses authoritative Buyer API presentation contracts" "HTTPS/JSON"
nexa.operationsMobile -> nexa.applicationApi.apiPresentation "Uses authoritative API presentation contracts" "HTTPS/JSON; V1 TARGET"
nexa.buyerMobile -> nexa.applicationApi.apiPresentation "Uses authoritative Buyer API presentation contracts" "HTTPS/JSON; V1 TARGET"
nexa.applicationApi -> nexa.postgresqlDatabase "Reads and writes scoped transactional state" "SQL/JDBC"
nexa.applicationApi -> nexa.objectStorage "Stores and retrieves authorized evidence and documents" "S3-compatible API"
nexa.applicationApi -> paymentProvider "Uses payment ACL" "Provider API / HTTPS"
nexa.applicationApi -> emailDeliveryService "Uses email ACL" "Provider API / HTTPS"
nexa.applicationApi -> mapsGeolocationProvider "Uses maps/geolocation ACL" "Provider API / HTTPS"

nexa.applicationApi.apiPresentation -> nexa.applicationApi.apiAccessContext "Resolves authenticated identity and requested scope"
nexa.applicationApi.apiPresentation -> nexa.applicationApi.apiApplication "Invokes typed commands and queries"
nexa.applicationApi.apiApplication -> nexa.applicationApi.apiDomain "Applies domain policies and transitions"
nexa.applicationApi.apiApplication -> nexa.applicationApi.apiAccessContext "Requires authorized execution context"
nexa.applicationApi.apiApplication -> nexa.applicationApi.apiPersistence "Uses repositories and transaction ports"
nexa.applicationApi.apiApplication -> nexa.applicationApi.apiIntegrations "Uses provider/device ports"
nexa.applicationApi.apiApplication -> nexa.applicationApi.apiReliability "Records durable facts and projections"
nexa.applicationApi.apiDomain -> nexa.applicationApi.apiReliability "Produces domain facts for publication"
nexa.applicationApi.apiAccessContext -> nexa.applicationApi.apiPersistence "Scopes reads/writes and RLS context"
nexa.applicationApi.apiPersistence -> nexa.postgresqlDatabase "Reads and writes scoped state"
nexa.applicationApi.apiReliability -> nexa.postgresqlDatabase "Stores outbox, inbox, leases and projections"
nexa.applicationApi.apiIntegrations -> paymentProvider "Uses payment ACL"
nexa.applicationApi.apiIntegrations -> emailDeliveryService "Uses email ACL"
nexa.applicationApi.apiIntegrations -> mapsGeolocationProvider "Uses maps/geolocation ACL"
nexa.applicationApi.apiIntegrations -> nexa.objectStorage "Uses storage and evidence ACL"
nexa.applicationApi.apiApplication -> nexa.applicationApi.targetCommercialCommitment "Maps Commercial Commitment ownership to application workflows"
nexa.applicationApi.apiApplication -> nexa.applicationApi.targetInventoryAvailability "Maps Inventory Availability ownership to application workflows"
nexa.applicationApi.apiApplication -> nexa.applicationApi.targetFulfillmentDelivery "Maps Fulfillment and Delivery ownership to application workflows"
nexa.applicationApi.apiApplication -> nexa.applicationApi.targetCreditReceivables "Maps Credit and Receivables ownership to application workflows"
nexa.applicationApi.apiApplication -> nexa.applicationApi.targetPaymentDocuments "Maps Payments and Business Documents ownership to application workflows"
nexa.applicationApi.apiApplication -> nexa.applicationApi.targetNotificationTraceability "Maps Notifications and Traceability ownership to application workflows"
nexa.applicationApi.targetCommercialCommitment -> nexa.applicationApi.targetInventoryAvailability "Requires atomic inventory protection"
nexa.applicationApi.targetCommercialCommitment -> nexa.applicationApi.targetCreditReceivables "Requires applicable atomic credit decision"
nexa.applicationApi.targetCommercialCommitment -> nexa.applicationApi.targetFulfillmentDelivery "Passes confirmed order execution intent"
nexa.applicationApi.targetInventoryAvailability -> nexa.applicationApi.targetFulfillmentDelivery "Supplies Physical Allocation contract"
nexa.applicationApi.targetPaymentDocuments -> nexa.applicationApi.targetCreditReceivables "Applies confirmed Payment to Receivable by stable reference"
nexa.applicationApi.targetFulfillmentDelivery -> nexa.applicationApi.targetNotificationTraceability "Publishes committed operational facts after transaction"

nexa.internalWebPlatform.platformRouting -> nexa.internalWebPlatform.platformAuthorization "Applies surface/capability navigation"
nexa.internalWebPlatform.platformRouting -> nexa.internalWebPlatform.platformShell "Selects authenticated shell"
nexa.internalWebPlatform.platformShell -> nexa.internalWebPlatform.platformFeatureState "Hosts feature projections"
nexa.internalWebPlatform.platformAuthorization -> nexa.internalWebPlatform.platformFeatureState "Controls action availability"
nexa.internalWebPlatform.platformFeatureState -> nexa.internalWebPlatform.platformApiClients "Loads and mutates API state"
nexa.internalWebPlatform.platformApiClients -> nexa.applicationApi.apiPresentation "Uses HTTP/API contracts"
nexa.internalWebPlatform.platformFeatureState -> nexa.internalWebPlatform.platformSharedExperience "Renders state and accessibility primitives"

nexa.buyerPortal.portalRouting -> nexa.buyerPortal.portalAuthorization "Applies relationship navigation"
nexa.buyerPortal.portalRouting -> nexa.buyerPortal.portalShell "Selects authenticated Buyer shell"
nexa.buyerPortal.portalShell -> nexa.buyerPortal.portalFeatureState "Hosts Buyer projections"
nexa.buyerPortal.portalAuthorization -> nexa.buyerPortal.portalFeatureState "Controls allowed actions"
nexa.buyerPortal.portalFeatureState -> nexa.buyerPortal.portalApiClients "Loads and mutates Buyer API state"
nexa.buyerPortal.portalApiClients -> nexa.applicationApi.apiPresentation "Uses Buyer HTTP/API contracts"
nexa.buyerPortal.portalFeatureState -> nexa.buyerPortal.portalSharedExperience "Renders state and accessibility primitives"

nexa.operationsMobile.operationsPresentation -> nexa.operationsMobile.operationsApplication "Invokes explicit client use cases"
nexa.operationsMobile.operationsApplication -> nexa.operationsMobile.operationsRepositories "Uses client data boundary"
nexa.operationsMobile.operationsApplication -> nexa.operationsMobile.operationsDeviceAdapters "Uses device capabilities through adapters"
nexa.operationsMobile.operationsApplication -> nexa.operationsMobile.operationsBackgroundRetry "Schedules only safe retryable client work"
nexa.operationsMobile.operationsRepositories -> nexa.operationsMobile.operationsRemoteDataSource "Reads and writes API contract data"
nexa.operationsMobile.operationsRepositories -> nexa.operationsMobile.operationsLocalState "Reads/writes safe client-local state and staging"
nexa.operationsMobile.operationsBackgroundRetry -> nexa.operationsMobile.operationsRepositories "Reuses explicit retry and freshness policy"
nexa.operationsMobile.operationsRemoteDataSource -> nexa.applicationApi.apiPresentation "Uses authoritative Nexa API contracts"
nexa.buyerMobile.buyerPresentation -> nexa.buyerMobile.buyerApplication "Invokes explicit client use cases"
nexa.buyerMobile.buyerApplication -> nexa.buyerMobile.buyerRepositories "Uses client data boundary"
nexa.buyerMobile.buyerApplication -> nexa.buyerMobile.buyerPlatformAdapters "Uses platform capabilities through adapters"
nexa.buyerMobile.buyerRepositories -> nexa.buyerMobile.buyerRemoteServices "Reads and writes API contract data"
nexa.buyerMobile.buyerRepositories -> nexa.buyerMobile.buyerLocalState "Reads/writes safe projections and harmless drafts"
nexa.buyerMobile.buyerRemoteServices -> nexa.applicationApi.apiPresentation "Uses authoritative Portal/Nexa API contracts"
