services:
  structurizr:
    image: structurizr/structurizr:2026.06.28
    command: local
    ports:
      - "9090:8080"
    volumes:
      - ../../01-shared/architecture/c4/structurizr:/usr/local/structurizr
